CREATE DATABASE SistemaCafeteriaDb
GO

USE SistemaCafeteriaDb
GO

CREATE TABLE Usuario(
UsuarioId INT IDENTITY PRIMARY KEY,
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(255) UNIQUE NOT NULL,
Senha VARBINARY(MAX) NOT NULL,
)
GO

SELECT * FROM Usuario

CREATE TABLE ItensCafeteria (
ItemId INT IDENTITY PRIMARY KEY,
Nome VARCHAR(100) NOT NULL,
Descricao NVARCHAR(MAX) NOT NULL,
Preco DECIMAL(9) NOT NULL
)
GO

SELECT * FROM ItensCafeteria